name: Delpoy

on: [push]

jobs:
  build:
    docker:
      - image: circleci/python:3.10.7
    working_directory: ~/repo

    steps:
      - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      
      - run:
        name: run tests
        command: |
          . venv/bin/activate
          python -m unnittest -v ./test/test_number_utils.py
          nose2 -v --with-coverage
          nose2 -v --with-coverage --coverage-report html
