name: Delpoy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.7"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Testing Codes
        run: |
          python -m pip install nose2 coverage
          cd project
          nose2 -v --with-coverage
          nose2 -v --with-coverage --coverage-report html