version: 2.1
orbs:
  python: circleci/python@3.10.7

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .


workflows:
  test_app:
    jobs:
      - run:
        name: install dependencies
        command: python3 -m venv venv  . venv/bin/activate 
        command: pip install -r requirements.txt
      - run:
          name: run tests
          command: . venv/bin/activate
          command:  python -m unittest discover ./tests/
          command:  coverage html -d test-reports
          command:  coverage run -m unittest discover ./tests/
            
